### ISSUE TITLE
Move to collective?

### ISSUE THREAD

**Issue by gforcada** [plone/plone.versioncheck#1]
@jensens is there any reason to create it on plone org rather than on collective org? I mean to lower the entry barrier (not sure if that's much of an issue given the scope of the project).

**Comment by jensens** [comment]
hmm, ok, just because it was in buildout.coredev before. but as i was the only person committing on it it could be moved to collective.

**Comment by jensens** [comment]
i think its fine if we keep this in the  plone  repo
