### ISSUE TITLE
Wrong result for active pinn

### ISSUE THREAD

**Issue by pbauer** [plone/plone.versioncheck#14]
First of all: Thanks for this, I love it! Especially the -r switch is totally awsome!
The order and the resolution of the active version is still wrong. 

What I get is:
```
setuptools
    18.5 ................. A http://dist.plone.org/release/5.0.2/versions.cfg
    0.6c11 ............... I http://dist.plone.org/versions/zopetoolkit-1-0-8-ztk-versions.cfg
    19.2 ................. I https://raw.githubusercontent.com/starzel/buildout/5.0.2/linkto/floating_versions.cfg
    19.4 ................. I floating_versions_project.cfg
    19.1 ................. I pinned_versions_project.cfg
```
The active version is in fact not ``18.5`` but ``19.1`` which is pinned by ``pinned_versions_project.cfg``. 

I'm still not clear how the pinns are sorted. A order where the later overides the former would be:
```
setuptools
    0.6c11 ............... I http://dist.plone.org/versions/zopetoolkit-1-0-8-ztk-versions.cfg
    18.5 ................. I http://dist.plone.org/release/5.0.2/versions.cfg
    19.2 ................. I https://raw.githubusercontent.com/starzel/buildout/5.0.2/linkto/floating_versions.cfg
    19.4 ................. I floating_versions_project.cfg
    19.1 ................. A pinned_versions_project.cfg
```

**Comment by jensens** [comment]
> The order and the resolution of the active version is still wrong. 

I see, youre right. Theres a bug left. I will fix it now. The weighting in the order of extends is the problem.

> I'm still not clear how the pinns are sorted. A order where the later overides the former would be

Order is how they are in the extends chain, example, given in each a version of ``my.pkg`` was declared

1. buildout.cfg (3.0.3)
2  buildout.cfg extends foo.cfg (3.0.1)
3. buildout.cfg extends bar.cfg (2.0)
5. foo cfg. extends baz.cfg (3.1)
6. found a newer major version at pypi (4.0)
7. found a newer minor version at pypi (3.2)
8. found a newer major prerelease version at pypi (5.1b2)

The we get (after I fixed the bug above)::

    my.pkg
        3.0.3............... A buildout.cfg
        2.0 ................ I bar.cfg
        3.0.1 .............. I foo.cfg
        3.1 ................ I baz.cfg
        4.0 ................ U Major        
        3.2 ................ U Minor
        5.1b2............... P Majorpre

I think I'll put this into the README. For me this is the most logical way to analyse what happens in my buildout.

Do you think it makes sense to add a sort option to sort after version? Personally I do not need it. But if so, please create a new issue as feature tagged "Enhancement". Technically its not difficult.

**Comment by pbauer** [comment]
Great! I can confirm that it works now. 

```
setuptools
    19.1 ................. A pinned_versions_project.cfg
    19.4 ................. I floating_versions_project.cfg
    19.2 ................. I https://raw.githubusercontent.com/starzel/buildout/5.0.2/linkto/floating_versions.cfg
    18.5 ................. I http://dist.plone.org/release/5.0.2/versions.cfg
    0.6c11 ............... I http://dist.plone.org/versions/zopetoolkit-1-0-8-ztk-versions.cfg
```
