### ISSUE TITLE
release with python 3 support

### ISSUE THREAD

**Issue by gforcada** [plone/plone.versioncheck#24]
Any attempt to run bin/buildout on buildout.coredev with python 3 fails as early as trying to load plone.versioncheck, as it is not python 3 compatible.

**Comment by loechel** [comment]
Hi @gforcada Commit https://github.com/plone/plone.versioncheck/commit/3830a1cf04e6dea4943c627e580ef5d6dc92312f added Python 3 Support. At least I have get it run with this on Python 3.5

**Comment by gforcada** [comment]
Great!

@jensens can we get a release? :-)
El dia 19/05/2016 9:59, "Alexander Loechel" <notifications@github.com> va
escriure:

**Comment by jensens** [comment]
@gforcada I'am a bit short with time as you may know :( but I gave you permissions on pypi for this package.

**Comment by gforcada** [comment]
@jensens, ok I will give it a try.

**Comment by gforcada** [comment]
Release done: https://pypi.python.org/pypi/plone.versioncheck
