### ISSUE TITLE
limit results to pins located in a certain config file

### ISSUE THREAD

**Issue by frisi** [plone/plone.versioncheck#27]
just stumbled upon plone.versioncheck and i'm used to z3c.checkversion.

my usecase is to find newer versions for packages that i've pinned manually in a separate versions.cfg file.
i'm usually not interested if there are newer versions for packages pinned in plone or zope release version files (ie. http://dist.plone.org/release/4.3.11/versions.cfg)

is there a way to limit the output to packages pinned in a certain configuration file?

something like `bin/versioncheck -p -n --pin-file=versions/versions.cfg buildout.cfg`

**Comment by loechel** [comment]
@frisi any idea how the report should look like, or is it exactly the same, report just with only those packages, that where found in your pin-file input?

**Comment by jensens** [comment]
I added a feature to exclude files with a pattern matching. I think this in the direction this ticket direct to and close it.
