### ISSUE TITLE
versioncheck does not report newest version

### ISSUE THREAD

**Issue by frisi** [plone/plone.versioncheck#28]
i've got a buildout with `collective.quickupload` pinned to version 1.5.8

the report shows that there is an update to 1.9.0 available althouth the current version is https://pypi.python.org/pypi/collective.quickupload/1.10.0 (available for a month already - so caching pypi results can't be an issue as i installed the package for the first time yesterday)

i guess the problem is string comparison `'10' < '9'` VS numbers `9 < 10` here

**Comment by loechel** [comment]
Problem is different, return JSON-Data is not ordered and any newer version has always overwritten the result set.

Problem is fixed in #29. Needs review and pull.
