### ISSUE TITLE
Sorting and coloring of versions is confusing

### ISSUE THREAD

**Issue by pbauer** [plone/plone.versioncheck#3]
How are the versions sorted? Here is an example from a buildout that confuses me:

![setuptools](https://cloud.githubusercontent.com/assets/453208/12306322/6f563430-ba39-11e5-918b-c748d502780f.png)

The example-project uses setuptools 9.1 (line 4, yellow). I assumed the first line is overwritten by the second an so forth (except for the pypi-lines) but http://dist.plone.org/versions/zopetoolkit-1-0-8-ztk-versions.cfg is not overriding http://dist.plone.org/release/5.0.2/versions.cfg but the other way around. If the order is the order of overrides with the last one being the used version the correct order should be:

    0.6c11................ http://dist.plone.org/versions/zopetoolkit-1-0-8-ztk-versions.cfg
    18.5.................. http://dist.plone.org/release/5.0.2/versions.cfg
    19.2.................. https://raw.githubusercontent.com/starzel/buildout/5.0.2/linkto/floating_versions.cfg
    19.1.................. pinned_versions_project.cfg
    19.2.................. major (PyPI)
    18.8.1................ minor (PyPI)

Also: Why are line 3 *and* 4 yellow? And why is the package-name red?

**Comment by jensens** [comment]
Agree and I plan to change this partly and document it.

**Comment by pbauer** [comment]
Great, thanks!

**Comment by jensens** [comment]
latest is on top, colors explaine already (and took - imo - better color assignement)
