### ISSUE TITLE
When installed I can`t start plone instance 

### ISSUE THREAD

**Issue by krissik** [plone/plone.versioncheck#6]
First of all: Thanks for this!

After I have installed plone.versioncheck I can`t start my instance anymore ( bin/versioncheck is working):
```
> bin/instance fg
Traceback (most recent call last):
  File "bin/instance", line 265, in <module>
    import plone.recipe.zope2instance.ctl
ImportError: No module named recipe.zope2instance.ctl
```

If I uninstall it I can start the instance again (without running buildout again)

```
xyz@pc ~/projects/plone/plone5-buildout:
> bin/pip uninstall plone.versioncheck
Uninstalling plone.versioncheck:
 ...
Proceed (y/n)? y
  Successfully uninstalled plone.versioncheck
xyz@pc ~/projects/plone/plone5-buildout:
> bin/instance fg
2016-01-14 15:39:16 INFO ZServer HTTP server started at Thu Jan 14 15:39:16 2016
	Hostname: 0.0.0.0
	Port: 8082
```

I am using virtualenv. I have created the virtualenv to the directory my buildout files are in. (if that matters)

Update: I have installed it to the same virtualenv plone uses. If I install it to system python it works. Maybe there is a conflict with the namespace `plone`?

**Comment by jensens** [comment]
I can not reproduce it here. Can you give me instructions how to get to the failure?

**Comment by jensens** [comment]
@KrissiK is this still the case?

**Comment by KrissiK** [comment]
I have got still the problem and hope this helps to reproduce it:

```
git clone https://github.com/collective/minimalplone5.git
cd minimalplone5
virtualenv .
bin/pip install zc.buildout==2.4.3 # 2.5.0 not working - no idea why
bin/buildout
bin/instance --help # working
bin/instance fg # working
bin/pip install plone.versioncheck
bin/versioncheck buildout.cfg # working
bin/instance --help # ImportError: No module named recipe.zope2instance.ctl
bin/pip uninstall plone.versioncheck
bin/instance --help # again working
```

**Comment by ale-rt** [comment]
It is related to a namespace clash.

When plone.versioncheck is installed in the virtualenv, it will hide all the other modules in the namespace plone.
You probably should install it in another virtualenv or using buildout as suggested in the README:
```ini
[ploneversioncheck]
recipe = zc.recipe.egg
eggs = plone.versioncheck
```

**Comment by jensens** [comment]
So its a namespace package in ``src/plone/__init__.py`` and also declared as such in ``setup.py`` - no idea what is wrong. Any ideas/hints?

**Comment by jensens** [comment]
edge case/ wrong usage
