### ISSUE TITLE
Available update from 'lazy' 1.0 to 1.2 is not found

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.versioncheck#7]
Awesome! I used z3c.checkversions before, but plone.versions has a few more handy options.

I have a buildout where I have pinned `lazy = 1.0` and the script does not find the new version 1.2.

I tried to come up with a small test buildout to show it, but strangely there it does not report any outdated versions, even though I added an extra outdated one (colorama):

```
[buildout]
show-picked-versions = true
parts =
    plone-versioncheck
    lazy
versions = versions

[versions]
colorama = 0.3.3
lazy = 1.0
plone.versioncheck = 1.0
requests = 2.9.1
setuptools = 19.3
zc.buildout = 2.5.0
zc.recipe.egg = 2.0.3

[lazy]
recipe = zc.recipe.egg
eggs = lazy

[plone-versioncheck]
recipe = zc.recipe.egg
eggs = plone.versioncheck
```

Running buildout works fine but the script reports nothing:

```
$ bin/buildout 
...
Installing plone-versioncheck.
Generated script '/Users/maurits/tmp/check/bin/versioncheck'.
Installing lazy.
$ bin/versioncheck
Check Versions
--------------
$ bin/versioncheck -p
Check Versions
--------------
```

It works fine on a few other buildouts I tried it with.

O, it could be that PyPI is doing some limiting. In a different buildout the script reported an update for z3c.dependencychecker from 1.5 to 1.9. After updating the pin and running it again, it shows an update from 1.9 to 1.15.

**Comment by jensens** [comment]
hmm https://pypi.python.org/pypi/lazy/1.2/json looks ok, so this looks like a bug in plone.versioncheck.

**Comment by mauritsvanrees** [comment]
That works, thanks.
